# File: /Users/lawsonprendergast/quant-training/ql_wrapper/models.py

class MonteCarloModel:
    ...
    def delta(self, instrument, num_paths, bump=0.01, seed=None, antithetic=True):
        ...
        up_price, _ = self.price_and_se(instrument, num_paths=num_paths, seed=seed, antithetic=antithetic)
        ...
        dn_price, _ = self.price_and_se(instrument, num_paths=num_paths, seed=seed, antithetic=antithetic)
        ...